# BUCKET - ASSET THREE
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-three-3
spec:
  title: ASSET THREE
  description: Describe your new bucket
  icon: view_stream
  primary: title
  readOnly: false
  history: false
  properties:
    title:
      type: string
      title: title
      description: Title of the row
      options:
        position: left
  acl:
    write: true==true
    read: true==true
  order: 2
---
# BUCKET - ASSET ONE
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-one-1
spec:
  title: ASSET ONE
  description: Describe your new bucket
  icon: view_stream
  primary: title_1
  readOnly: false
  history: false
  properties:
    title_1:
      type: string
      title: title_1
      description: Description of the title_1 input
      options:
        position: bottom
    obj:
      type: object
      title: obj
      description: Description of the obj input
      options:
        position: bottom
      properties:
        relation_one:
          type: relation
          title: relation_one
          description: Description of the relation_one input
          options:
            position: bottom
          relationType: onetoone
          dependent: false
          bucket:
            resourceFieldRef:
              schemaName: asset-three-3
  acl:
    write: true==true
    read: true==true
  order: 0
---
# BUCKET - ASSET THREE
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-three-3
spec:
  title: ASSET THREE
  description: Describe your new bucket
  icon: view_stream
  primary: title
  readOnly: false
  history: false
  properties:
    title:
      type: string
      title: title
      description: Title of the row
      options:
        position: left
    relation_three:
      type: relation
      title: relation_three
      description: Description of the relation_three input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: asset-one-1
  acl:
    write: true==true
    read: true==true
  order: 2
---
# BUCKET - ASSET TWO
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-two-2
spec:
  title: ASSET TWO
  description: Describe your new bucket
  icon: view_stream
  primary: title_2
  readOnly: false
  history: false
  properties:
    title_2:
      type: string
      title: title_2
      description: Description of the title_2 input
      options:
        position: bottom
    obj:
      type: object
      title: obj
      description: Description of the obj input
      options:
        position: bottom
      properties:
        relation_two:
          type: relation
          title: relation_two
          description: Description of the relation_two input
          options:
            position: bottom
          relationType: onetoone
          dependent: false
          bucket:
            resourceFieldRef:
              schemaName: asset-three-3
  acl:
    write: true==true
    read: true==true
  order: 1