# FUNCTION - Test Function
apiVersion: function/v1
kind: Function
metadata:
  name: test-function-function
spec:
  language: javascript
  timeout: 60
  dependency: []
  title: Test Function
  code: ./function/test-function-function.js
  runtime:
    name: Node
    language: Javascript
---
# TRIGGER - default
apiVersion: function/v1
kind: Trigger
metadata:
  name: default
spec:
  type: firehose
  active: true
  name: default
  func: test-function-function
  firehoseOptions:
    event: "*"
---
# TRIGGER - testHandler
apiVersion: function/v1
kind: Trigger
metadata:
  name: testHandler
spec:
  type: schedule
  active: true
  name: testHandler
  func: test-function-function
  scheduleOptions:
    timezone: Europe/Istanbul
    frequency: 0 0 * 1 *