# BUCKET - TestRelation_One
apiVersion: bucket/v1
kind: Schema
metadata:
  name: testrelation_one-bucket
spec:
  title: TestRelation_One
  description: Describe your new bucket
  icon: view_stream
  primary: title
  readOnly: false
  history: false
  properties:
    title:
      type: string
      title: title
      description: Description of the title input
      options:
        position: bottom
    relation_one:
      type: relation
      title: relation_one
      description: Description of the relation_one input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: testrelation_two-bucket
  acl:
    write: true==true
    read: true==true
  order: 27
---
# BUCKET - TestRelation_Two
apiVersion: bucket/v1
kind: Schema
metadata:
  name: testrelation_two-bucket
spec:
  title: TestRelation_Two
  description: Describe your new bucket
  icon: view_stream
  primary: title
  readOnly: false
  history: false
  properties:
    title:
      type: string
      title: title
      description: Title of the row
      options:
        position: left
    relation_two:
      type: relation
      title: relation_two
      description: Description of the relation_two input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: testrelation_one-bucket
  acl:
    write: true==true
    read: true==true
  order: 28