# BUCKET - ASSET ONE
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-one-1
spec:
  title: ASSET ONE
  description: Describe your new bucket
  icon: view_stream
  primary: title_1
  readOnly: false
  history: false
  properties:
    title_1:
      type: string
      description: Description of the title_1 input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 0
---
# BUCKET - ASSET ONE
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-one-1
spec:
  title: ASSET ONE
  description: Describe your new bucket
  icon: view_stream
  primary: title_1
  readOnly: false
  history: false
  properties:
    title_1:
      type: string
      description: Description of the title_1 input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 0
---
# BUCKET - ASSET TWO
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-two-2
spec:
  title: ASSET TWO
  description: Describe your new bucket
  icon: view_stream
  primary: title_2
  readOnly: false
  history: false
  properties:
    title_2:
      type: string
      description: Description of the title_2 input
      options:
        position: bottom
    relation_two:
      type: relation
      description: Description of the relation_two input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: asset-one-1
  acl:
    write: true==true
    read: true==true
  order: 1