# BUCKET - ASSET ONE
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-one
spec:
  title: ASSET ONE
  description: Describe your new bucket
  icon: view_stream
  primary: title_1
  readOnly: false
  history: false
  properties:
    title_1:
      type: string
      title: title_1
      description: Description of the title_1 input
      options:
        position: bottom
    arr:
      type: array
      title: arr
      description: Description of the arr input
      options:
        position: bottom
      items:
        title: Title of the items
        type: object
        properties:
          name:
            type: string
            title: name
            description: Description of the name input
            options:
              position: bottom
  acl:
    write: true==true
    read: true==true
  order: 0
---
# BUCKET - ASSET TWO
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-two
spec:
  title: ASSET TWO
  description: Describe your new bucket
  icon: view_stream
  primary: title_2
  readOnly: false
  history: false
  properties:
    title_2:
      type: string
      title: title_2
      description: Description of the title_2 input
      options:
        position: bottom
    obj:
      type: object
      title: obj
      description: Description of the obj input
      options:
        position: bottom
      properties: {}
  acl:
    write: true==true
    read: true==true
  order: 1
---
# BUCKET - ASSET ONE
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-one
spec:
  title: ASSET ONE
  description: Describe your new bucket
  icon: view_stream
  primary: title_1
  readOnly: false
  history: false
  properties:
    title_1:
      type: string
      title: title_1
      description: Description of the title_1 input
      options:
        position: bottom
    arr:
      type: array
      title: arr
      description: Description of the arr input
      options:
        position: bottom
      items:
        title: Title of the items
        type: object
        properties:
          relation_one:
            type: relation
            title: relation_one
            description: Description of the relation_one input
            options:
              position: bottom
            relationType: onetoone
            dependent: false
            bucket:
              resourceFieldRef:
                schemaName: asset-one
          name:
            type: string
            title: name
            description: Description of the name input
            options:
              position: bottom
  acl:
    write: true==true
    read: true==true
  order: 0
---
# BUCKET - ASSET TWO
apiVersion: bucket/v1
kind: Schema
metadata:
  name: asset-two
spec:
  title: ASSET TWO
  description: Describe your new bucket
  icon: view_stream
  primary: title_2
  readOnly: false
  history: false
  properties:
    title_2:
      type: string
      title: title_2
      description: Description of the title_2 input
      options:
        position: bottom
    obj:
      type: object
      title: obj
      description: Description of the obj input
      options:
        position: bottom
      properties:
        relation_two:
          type: relation
          title: relation_two
          description: Description of the relation_two input
          options:
            position: bottom
          relationType: onetoone
          dependent: false
          bucket:
            resourceFieldRef:
              schemaName: asset-three
  acl:
    write: true==true
    read: true==true
  order: 1
---
# FUNCTION - Taxi Ride Accept
apiVersion: function/v1
kind: Function
metadata:
  name: taxi-ride-accept
spec:
  description: Seto ride accept
  language: javascript
  timeout: 50
  environment:
    - name: STRIPE_PAYMENT_METHOD_ID
      value: 5fe44ef6dfdd0f002c91efd7
    - name: STRIPE_PAYMENT_BUCKET
      value: 60953e7ba55024002c751a53
    - name: STRIPE_CUSTOMER_BUCKET
      value: 60953e73a55024002c751a4e
    - name: STRIPE_CARD_BUCKET
      value: 60953e75a55024002c751a4f
    - name: SECRET_API_KEY
      value: 5ks9718kiybw51i
    - name: TAXI_RIDE_BUCKET
      value: 5fe44b3bdfdd0f002c91efc9
    - name: GOOGLE_MAP_API_KEY
      value: AIzaSyDem6KpKY6-1Y68c1o3r-paNJPGIujpeik
    - name: TAXI_COUPON_USER_BUCKET
      value: 601d2fc51f7cc7002cebe5cc
    - name: TAXI_COUPON_BUCKET
      value: 5fe5af73dfdd0f002c91f2da
  dependency:
    - name: "@spica-devkit/bucket"
      version: ^0.8.8
    - name: fast-json-patch
      version: ^3.0.0-1
    - name: node-fetch
      version: ^2.6.1
  title: Taxi Ride Accept
  code: ./function/taxi-ride-accept.js
  runtime:
    name: Node
    language: Javascript
---
# TRIGGER - rideAccept
apiVersion: function/v1
kind: Trigger
metadata:
  name: rideAccept
spec:
  type: bucket
  active: true
  batch:
    deadline: 45
    limit: 9007199254740991
  name: rideAccept
  func: taxi-ride-accept
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: taxi-ride-request
    type: UPDATE
---
# TRIGGER - rideUpdate
apiVersion: function/v1
kind: Trigger
metadata:
  name: rideUpdate
spec:
  type: bucket
  active: true
  batch:
    deadline: 45
    limit: 9007199254740991
  name: rideUpdate
  func: taxi-ride-accept
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: taxi-ride
    type: UPDATE